### ISSUE TITLE
only works with java 1.8 or later which i already have but still doesn't work

### ISSUE THREAD

**Issue by Ayo0mide** [atom/ide-java#102]
A few things to know before you create an issue

* We launch a "language server" process on your machine that understands the language you are editing
* What that server can do - syntax compatibility, whether it supports formatting or outlines etc - is outside of our control
* You can see what the language server supports by checking out our README and following the link after "powered by"

If you understand these constraints, please remove this text and start writing your issue :)

**Comment by 50Wliu** [comment]
We need more information to help solve this issue. I'm going to close this for now but if you're still having trouble please let us know!
