### ISSUE TITLE
IDE-JAVA within Atom, fails to recognise lombok even after adding extraargs in package.json

### ISSUE THREAD

**Issue by kcsarath** [atom/ide-java#107]
I am trying to use spring boot projects through Atom and added the STS plugin. My project uses lombok and my eclipse is able to recognise lombok fine.

For ATOM, I edited the 
**~/.atom/packages/ide-java/package.json** 
to add an extraArgs

`"properties": {
        "extraArgs": {
          "type": "string",
          "default": "-noverify -javaagent:/path/to/lombok.jar -Xbootclasspath/a:/path/to/lombok.jar -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication",
          "description": "Extra arguments passed to the Java VM when launching the Java Language Server. Eg. use `-noverify -Xmx1G  -XX:+UseG1GC -XX:+UseStringDeduplication` to bypass class verification, increase the heap size to 1GB and enable String deduplication with the G1 Garbage collector."
        }
      }`

Despite this, when I open a java file having a lombok import, it complains that import lombok.*;  cannot be resolved. 

My maven project is updated with the relevant lombok dependency 
```
  <dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.18.8</version>
			<scope>provided</scope>
    </dependency>
```

**Comment by 50Wliu** [comment]
You should instead change the extra args in the Settings View: Settings -> Packages -> IDE Java. Does that work?

**Comment by kcsarath** [comment]
Looks like it worked. Thank you.
