### ISSUE TITLE
Cannot save Java-files when languageserver is running

### ISSUE THREAD

**Issue by mdiin** [atom/ide-java#115]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

After the Java language server has started, attempting to save Java-files results in an error.

### Steps to Reproduce

1. Open any Java file
2. Wait for languageserver to be running
3. Save file

**Expected behavior:**

I would expect the file to be saved.

**Actual behavior:**

In the UI, nothing happens.

In the developer console, this error is visible:

```
Uncaught (in promise) TypeError: Cannot read property 'Manual' of undefined
    at TextEditorSyncAdapter.willSave (document-sync-adapter.ts:331)
    at Function.simpleDispatch (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:64)
    at /usr/lib/atom/node_modules/event-kit/dist/emitter.js:270
    at Array.map (<anonymous>)
    at Emitter.emitAsync (/usr/lib/atom/node_modules/event-kit/dist/emitter.js:269)
    at TextBuffer.saveTo (/usr/lib/atom/node_modules/text-buffer/lib/text-buffer.js:1923)
willSave @ document-sync-adapter.ts:331
simpleDispatch @ /usr/lib/atom/node_modules/event-kit/dist/emitter.js:64
(anonymous) @ /usr/lib/atom/node_modules/event-kit/dist/emitter.js:270
emitAsync @ /usr/lib/atom/node_modules/event-kit/dist/emitter.js:269
saveTo @ /usr/lib/atom/node_modules/text-buffer/lib/text-buffer.js:1923
```

**Reproduces how often:**

Every time.

### Versions

`atom --version`:
Atom    : 1.42.0
Electron: 4.2.12
Chrome  : 69.0.3497.128
Node    : 10.11.0

`apm --version`:
apm  2.4.5
npm  6.13.6
node 13.6.0 x64
atom 1.42.0
python 3.8.1
git 2.25.0

OS:
ArchLinux, kernel 5.4.10-arch1-1

### Additional Information

This was working last week, yet nothing on my atom install or OS has been updated since then. I have tried full reinstall, including reset of `~/.atom`, to no effect.

I think this is the proper project for this issue, since this is the project that includes the vscode-languageserver-protocol package, but it might not be?

**Comment by mdiin** [comment]
I think this might be an upstream issue with [atom-languageclient](https://github.com/atom/atom-languageclient), but confirmation would be welcome.

**Comment by mdiin** [comment]
Bumping the vscode-languageclient dependencies in the atom-languageclient node_module and running `npm install` inside that dependency's folder has "solved" the issue. After that, I tried bumping the `atom-languageclient` dependency of this project to 0.9.9. This also solved the issue (by transitive dependencies), which means that is probably the correct solution.

I still wonder why this happened though...

**Comment by MarceloLaser** [comment]
I am also having this issue but am not competent enough to apply any of what mdiin described as a solution. I would appreciate any help, as this has effectively made ide-java unusable for the time being.

**Comment by mdiin** [comment]
I don’t know if you got it working, but let me give you some more detailed steps. This assumes you are on a Linux OS.

1. ‘cd ~/.atom/packages/ide-java’
2. Open ‘packages.json’
3. Under the ‘dependencies’ key, find the line which says ‘atom-language client’ and up the version to ‘0.9.9’
4. Run ‘npm  install’

Now the Java IDE should use the newer dependency, and saving files should work again.

I hope this helps.

Matthias Varberg Ingesman

**Comment by rajivshah3** [comment]
Thanks @mdiin, I was running into this issue as well! I created a PR with the fix: https://github.com/atom/ide-java/pull/116

If anyone wants to apply this fix without needing to manually edit the package.json, follow these steps:

1. Find `ide-java` in the Packages section of Atom settings and uninstall it 
2. Open Terminal and run `apm install https://github.com/rajivshah3/ide-java`
3. Restart Atom

**Comment by grindarius** [comment]
> 
> 
> Thanks @mdiin, I was running into this issue as well! I created a PR with the fix: #116
> 
> If anyone wants to apply this fix without needing to manually edit the package.json, follow these steps:
> 
>     1. Find `ide-java` in the Packages section of Atom settings and uninstall it
> 
>     2. Open Terminal and run `apm install https://github.com/rajivshah3/ide-java`
> 
>     3. Restart Atom

So I tried your solution but when I run "apm install https://github.com/rajivshah3/ide-java"
It says
`Cloning https://github.com/rajivshah3/ide-java.git failed
Installing modules done
Cannot read property 'getReferenceTarget' of null`

and I don't quite get it why it doesn't work

**Comment by Tripp-Sautner** [comment]
Its probably cause @rajivshah3 uses a mac while Windows users might have to utilize a different way of getting around the issue, we need to add this directly to our path via System Variables though this PC system.

![image](https://user-images.githubusercontent.com/52726452/73222754-ff42eb00-4131-11ea-846e-0b2557a7feb0.png)


"%USERPROFILE%\AppData\Local\atom\bin"   <---- That

**Comment by Tripp-Sautner** [comment]
It might already be in your path

**Comment by rajivshah3** [comment]
﻿
It seems like it’s already in the PATH however. The error they’re reporting is a JavaScript error.

**Comment by grindarius** [comment]
> 
> 
> Its probably cause @rajivshah3 uses a mac while Windows users might have to utilize a different way of getting around the issue, we need to add this directly to our path via System Variables though this PC system.
> 
> ![image](https://user-images.githubusercontent.com/52726452/73222754-ff42eb00-4131-11ea-846e-0b2557a7feb0.png)
> 
> "%USERPROFILE%\AppData\Local\atom\bin" <---- That

I tried your method and still get the same error out of it. Maybe I need a fresh Windows installation?

**Comment by ytx21cn** [comment]
> I don’t know if you got it working, but let me give you some more detailed steps. This assumes you are on a Linux OS. 1. ‘cd ~/.atom/packages/ide-java’ 2. Open ‘packages.json’ 3. Under the ‘dependencies’ key, find the line which says ‘atom-language client’ and up the version to ‘0.9.9’ 4. Run ‘npm install’ Now the Java IDE should use the newer dependency, and saving files should work again. I hope this helps. Matthias Varberg Ingesman
> […](#)
> Den 22. jan. 2020 kl. 04.37 skrev Marcelo Laser ***@***.***>: ﻿ I am also having this issue but am not competent enough to apply any of what mdiin described as a solution. I would appreciate any help, as this has effectively made ide-java unusable for the time being. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

This fixed my issue as well.

**Comment by turneps403** [comment]
I met with this problem on macOS
`atom --version`
Atom    : 1.45.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0

And after the update node version to last 13.12.0 problem was solved.
So, in my case `brew upgrade node` resolved the problem

**Comment by howlettga** [comment]
I can't save any files when java-ide is installed as an extension for atom. i tried updating the dependency to 0.9.9 without success. I have node.js 12.x installed as I have to run the LTS version. Is node LTS not supported for ide-java? Running on Windows 10

**Comment by ParadoxV5** [comment]
When will the PR for this **severe** bug release?
