### ISSUE TITLE
Cannot save java files when JDT server is running.

### ISSUE THREAD

**Issue by grindarius** [atom/ide-java#118]
This happened about a month ago. When the JDT server is running. I cannot save the file. When I close the file, it asks me ``` Do you want to save it? ```
Then when I click ```save as```. It says ```Error: undefined```.

I tried all the methods from #115 But it doesn't work. Will there possibly be an update?

`atom --version`
Atom    : 1.44.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0

`apm --version`
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.44.0
python
git
visual studio

**Comment by grindarius** [comment]
Now I found the fixed file sorry

**Comment by mavericks52** [comment]
So i finally found how to fix the file on windows. 
1. Go to your `.atom\packages\ide-java\package.json` file.
2. Look for this in the .json file
```
"dependencies": {
    "atom-languageclient": "0.9.5",
    "atom-select-list": "^0.7.1",
    "decompress": "^4.2.0"
```
3. change the atom-languageclient from `0.9.5` to `0.9.9`
4. save the file
5. Shut down atom,
6. Go to command prompt and type `apm rebuild ide-java`. This will reinstall the ide-java package with the change you made.
7. Reopen atom. The issue should be fixed.
