### ISSUE TITLE
So i finally found how to fix the file save on windows.

### ISSUE THREAD

**Issue by mavericks52** [atom/ide-java#119]
So i finally found how to fix the file on windows. 
1. Go to your `.atom\packages\ide-java\package.json` file.
2. Look for this in the .json file
```
"dependencies": {
    "atom-languageclient": "0.9.5",
    "atom-select-list": "^0.7.1",
    "decompress": "^4.2.0"
```
3. change the atom-languageclient from `0.9.5` to `0.9.9`
4. save the file
5. Shut down atom,
6. Go to command prompt and type `apm rebuild ide-java`. This will reinstall the ide-java package with the change you made.
7. Reopen atom. The issue should be fixed.

_Originally posted by @mavericks52 in https://github.com/atom/ide-java/issues/118#issuecomment-586729823_

**Comment by ytx21cn** [comment]
Thanks. Also works on Ubuntu.

**Comment by lkashef** [comment]
Thanks @mavericks52 for the help and leaving a comment on the original post so people can find the solution in the future.

---

I am going to close this issue, as we treat our issues as our backlog, so it's suitable to be a comment on the original issue but not an issue on it's own.

**Comment by tiagosamaha** [comment]
Doesn´t work!

**Comment by NicoNex** [comment]
Thank you @mavericks52 you made my day.

**Comment by NicoNex** [comment]
Doesn't work for me either. :/

**Comment by marchingon12** [comment]
same here!
