### ISSUE TITLE
Leaving a java file to open a new one sends a shutdown request to the server

### ISSUE THREAD

**Issue by fbricon** [atom/ide-java#12]
It seems that Cmd+click on a Type (eg. java.lang.String) to open it causes the server to shutdown, throwing the error in #8. 
More simply, leaving an open Java file from a directory to open a new one (in the same project/directory) causes the same issue.

It happens consistently with Atom Beta 1.21.0-Beta0 + ide-java 0.6.0

**Comment by damieng** [comment]
Hmm, not able to repro this. Can you see anything in the dev tool windows pointing to an error?

**Comment by damieng** [comment]
Are you still seeing this with the latest version?
