### ISSUE TITLE
Cannot save file

### ISSUE THREAD

**Issue by teddybearrohan** [atom/ide-java#129]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

 File won't save - it says its undefined when I try to save as ; does nothing when I save

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

 save the file

**Actual behavior:**

 nothing happens

**Reproduces how often:**

 all the time

### Versions

 atom 1.50, macos catalina 10.15.6

### Additional Information

 disabling ide java package fixes it

**Comment by darangi** [comment]
@teddybearrohan I have tried reproducing this on atom 1.50 and macOS Catalina 10.15.6 but I couldn't.

**Comment by teddybearrohan** [comment]
After further investigation this appears to be an issue with atom itself. Looks like I'm switching back to visual studio for the time being.

**Comment by marchingon12** [comment]
This hopefully helps: 
https://github.com/atom/ide-java/issues/115#issuecomment-577034727
