### ISSUE TITLE
Update jdt.ls to the latest version

### ISSUE THREAD

**Issue by fbricon** [atom/ide-java#13]
ide-java 0.6.0 embeds a really, really, really old jdt.ls version (0.1.0.201704180126) :-)

Latest actual release is http://download.eclipse.org/jdtls/snapshots/jdt-language-server-0.3.0-201708311739.tar.gz (See newer builds on http://download.eclipse.org/jdtls/snapshots/?d)

FYI, there will be a new release (0.4.0) on Friday 15/09/2017.

**Comment by damieng** [comment]
That's great!  We'll pick up the new release soon. Hopefully that shutdown logging issue will make Friday's release.

**Comment by fbricon** [comment]
You can test this build (http://download.eclipse.org/jdtls/snapshots/jdt-language-server-0.4.0-201709122016.tar.gz) or more recent to see if the shutdown logging issue is fixed

**Comment by fbricon** [comment]
You can reach us on https://mattermost.eclipse.org/eclipse/channels/eclipsejdtls if you need help integrating with jdt.ls
