### ISSUE TITLE
Unable to install this package on latest Atom stable version

### ISSUE THREAD

**Issue by tobihagemann** [atom/ide-java#14]
Just read the blog post on the Atom IDE announcement and wanted to give it a try. I'm using Atom in the latest stable version `1.20.0`. I'm unable to install `ide-java` because it requires `1.21.0` or higher. Is this intended? Is this package only usable with Atom beta?

**Comment by damieng** [comment]
Yes, the packages are only for Atom Beta right now - stable does not have the necessary file watching api's or async shutdown necessary to make the experience stable.
