### ISSUE TITLE
Classpath is incomplete warning keeps coming up

### ISSUE THREAD

**Issue by apersonnamedmike** [atom/ide-java#15]
getting this warning on windows 10 on atom beta 1.21.0, and ide-java 0.6.0:
Classpath is incomplete. Only syntax errors will be reported
Eclipse JDT

When I googled how I might fix the error, I found this, which could be a similar issue: https://github.com/redhat-developer/vscode-java/issues/107

I think the linked issue could be related, but is there a current way to fix it, and if so, how?

**Comment by damieng** [comment]
The underlying language server expects to be able to identify the project itself so it understands scope etc.  

As there isn't a standard configuration for a Java 'project' it uses pom.xml - there may be some other alternatives but without digging in to the language server itself I can't be sure.

**Comment by apersonnamedmike** [comment]
Ah, that makes sense. thanks for clearing that up for me :)

**Comment by damieng** [comment]
I've checked in code that at least makes the help button on that dialog take you to the page that explains it. Will be in the next release.

**Comment by fuyutsuki** [comment]
I encountered the same situation.
On
```
OS: Win10 (x64)
Atom: Atom 1.21.0-beta0
Package: ide-java 0.6.0
Java: Java 144 (x64)
```
I`m looking forward to the future of Atom.

**Comment by vaerit094** [comment]
I have the same problem , Waiting some fix it.

**Comment by fbricon** [comment]
A more complete explanation is available at https://github.com/redhat-developer/vscode-java/wiki/%22Classpath-is-incomplete%22-warning

Each client of the Java Language Server need to deal with that warning.

**Comment by damieng** [comment]
From 0.6.1 we now display the error with a link to the documentation about why this error occurs and what you need to do to work around it.

**Comment by tylerFowler** [comment]
@damieng Using 0.6.4 I'm getting this pretty consistently. After working for a few days I suddenly started getting this error with my existing .classpath & .project files so I deleted them, now every time I open a Java file I get this warning. The project root does have a pom.xml file so it should be rebuilding but doesn't seem to be even attempting to rebuild the classpath config files.

Is there a way to force generation of new ones from the pom?

**Comment by damieng** [comment]
Sorry, we don't do anything specific with the classpath and POM - it all comes from the underlying JDT language server.  Any information on dealing with that should be available from the help button that comes up.

**Comment by tylerFowler** [comment]
Ah ok, wasn't sure if the building was initiated by this package. I'll take it up there, thanks!

**Comment by tylerFowler** [comment]
fwiw, I found I could regenerate the .project & .classpath files from IntelliJ but even with those files I get "Classpath incomplete" errors, even after reinstalling the package (and language server).

**Comment by cdstanford** [comment]
I still get this error every time a file opens even after
(1) clicking "Don't show again"
(2) restarting the window
(3) setting "Incomplete Classpath Severity" to `ignore` in settings

Has anyone else figured out how to fix this?
