### ISSUE TITLE
Cannot install ide-java

### ISSUE THREAD

**Issue by aprasadh** [atom/ide-java#23]
I tried installing `ide-java` using the `apm install ide-java` command, but received the following error message.
> `No available version compatible with the installed Atom version: 1.20.0`

I have already installed `atom-ide-ui`. What is the reason for this issue?

**Comment by damieng** [comment]
Yes, Atom IDE requires Atom 1.21 beta.  You can get the beta from https://atom.io/beta

**Comment by aprasadh** [comment]
Oh OK, Thanks. Then I will wait until it is out of beta. :)

BTW, why does atom-ide package installs (in 1.20) when it is not that useful for Java? Is the IDE capability available for other languages?

**Comment by damieng** [comment]
The atom-ide-ui packages were out for a while as earlier versions of Atom IDE worked in 1.19.

During early testing we found that the background language process used to analyze the files would not often not cleanly shutdown. Additionally the protocol requires that they be kept up to date with all changes to the file system.

Both of these issues required non-trivial work in Atom itself to facilitate (file monitoring and async package deactivation) and it was too late to put them into stable.  Additionally the package management system in Atom doesn't let us retroactively require newer versions of Atom.
