### ISSUE TITLE
Nothing is reported

### ISSUE THREAD

**Issue by simonepri** [atom/ide-java#25]
**Atom**: 1.21.0-beta0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6

![image](https://user-images.githubusercontent.com/3505087/30446838-981a51a8-998a-11e7-99b4-2bb13a6d9ee3.png)

The UI just show me this:
![image](https://user-images.githubusercontent.com/3505087/30446653-0c27e962-998a-11e7-9f8c-0e62494ef0cc.png)

But actually if I made some changes to my code, nothing is reported
![image](https://user-images.githubusercontent.com/3505087/30446685-2d3b3154-998a-11e7-9fc9-d2d9a84c273a.png)

The project where I'm trying it is configured with gradle

**Comment by damieng** [comment]
Do you changes include invalid Java?  The diagnostics will only report errors and warnings.

**Comment by simonepri** [comment]
@damieng yes of course. After a whole day of working the diagnostics started to "work" but every time I had to close and reopen atom to get it updated after a change in the code.

**Comment by perkarlberg** [comment]
I can second this issue report. As soon as I add files to the project, the new .java files will get no warnings/errors reported and no other IDE features like autocomplete or hyper-click to reference work either.

I can also reproduce the issue by switching branch, new files (that don't exist in previous branch) will not benefit from any IDE functionality. The bottom bar says "Java (Eclipse JDT) Ready" but nothing happens. Restarting Atom does not help, but rebooting the computer does.

Atom 1.24.0
OS-X 10.13.3
Java version: 1.8.0_162

**Comment by rsese** [comment]
> As soon as I add files to the project, the new .java files will get no warnings/errors reported and no other IDE features like autocomplete or hyper-click to reference work either.

Just to clarify, you're creating a new file, saving it as a `.java` file, but there are no diagnostics?  I gave this a try but wasn't able to reproduce.

> I can also reproduce the issue by switching branch, new files (that don't exist in previous branch) will not benefit from any IDE functionality.

I tried this as well but couldn't reproduce.

If you set `atom.config.set('core.debugLSP', true);` in devtools console and restart Atom, do you see any output when the IDE features stop working?

**Comment by damieng** [comment]
No response.

**Comment by thefzsalam** [comment]
I am experiencing the same problem.
It can be seen from the logs that diagnostics _are being reported_:

````
Java (Eclipse JDT) rpc.onNotification textDocument/publishDiagnostics Object {uri: "file:///home/farzeen/Projects/Mar_2018/libre-dl/src/main/java/in/fzs/libredl/app/MainActivity.java", diagnostics: Array(8)}
````

Here's an example of one such item: 
````
1 :Object
code: "536871240"
message: "The declared package "in.fzs.libredl.app" does not match the expected package "src.main.java.in.fzs.libredl.app""
range: Object
severity: 1
````

I am attaching the complete console log and a screenshot to show that no errors are actually shown in the UI.

Console Log:

[-1521867692650.log](https://github.com/atom/ide-java/files/1844051/-1521867692650.log)


Screenshot:

![2018-03-24-105849_1366x768_scrot](https://user-images.githubusercontent.com/12694111/37860759-5f60e45e-2f52-11e8-9c9e-f8d73ca0fa42.png)

**Comment by thefzsalam** [comment]
I used `Right Click->Save as` from console window to save the log.
It seems like the line breaks are all messed up to me.
Does anyone know a better way to save the complete log?

**Comment by damieng** [comment]
Do you have the atom-ide-ui package installed? It is required.

**Comment by thefzsalam** [comment]
Oh. I didn't have that installed. Installing now..

**Comment by thefzsalam** [comment]
Thanks for the quick reply. Everything working perfectly :+1:
