### ISSUE TITLE
Creating a new file does not work with java ide until file is reopened

### ISSUE THREAD

**Issue by seaside98** [atom/ide-java#32]
When you right click in the tree view and create a new java file, neither the linter or autocomplete works on the file until you close it and open it back up again.

Version 0.6.4

**Comment by damieng** [comment]
Hmm, this is actually going to be a problem over in atom-languageclient (also me, not shifting the blame - I'll just need to create an issue there and cross-link it here)

Good find, will be affecting all ide-x packages. I thought the grammar change detection would have fired when you save the file.  Did you choose the java grammar before saving?  Or just the moment you saved it started syntax highlighting but didn't state the ide services?

**Comment by fbricon** [comment]
be aware jdt.ls needs to be able to read the file from disk, so you can't get enhanced java support until the file is saved.

**Comment by damieng** [comment]
not even if we send the entire file contents over with the text doc sync message?

**Comment by fbricon** [comment]
No, I had it to work like that initially (it was pretty cool) but ran into a shitload of problems, so decided against.

**Comment by fbricon** [comment]
seems to be working now
