### ISSUE TITLE
So How can I use ide-java with atom?

### ISSUE THREAD

**Issue by akadark** [atom/ide-java#34]
I can't find anything except 'Java(Eclipse JDT) Ready' sign with a green light at the middle of the below. 

And is there any website or forum about atom ide? I couldn't get any information about it when I googled it.  If there is no instruction for this, it would be a good idea to make a step by step instruction for newbies. 

I'm so sorry to ask in here. I really wanna use it, but I couldn't find anywhere.

**Comment by damieng** [comment]
You'll need to install the atom-ide-ui package for things to have any kind of user interface.

**Comment by akadark** [comment]
Yeah, of course, I did download 'atom-ide-ui' first. then should I ask to how to use 'atom-ide-ui' in their repository? I thought 'atom-ide-ui' is just a basic package and ide-java is actually operating one.

**Comment by akadark** [comment]
Oh, I found the earlier issue like this. Thank you and sorry for annoying you!  

https://github.com/facebook-atom/atom-ide-ui/issues/60

**Comment by damieng** [comment]
You're not the first to ask so our documentation definitely is lacking -
we'll definitely look at a more comprehensive guide in the future.

**Comment by akadark** [comment]
Thank you for your kind answer! Actually, I thought atom-IDE meant compilable IDE but it might not. So It would be good to notify other guys about what you can't-do with this. just like gentle notifications or simple cautions.

**Comment by damieng** [comment]
We're going to get there - just lots of work to do and we wanted to get
helpful and useful features out as soon as we could as well as feedback and
contributions from our community.
