### ISSUE TITLE
Lombok Support and the like

### ISSUE THREAD

**Issue by tylerFowler** [atom/ide-java#39]
Is there any way to edit the VM args so that lombok can be supported?

For example in vscode-java there's this: https://github.com/redhat-developer/vscode-java/wiki/Lombok-support

I'm assuming there could be something similar here though I'm totally unfamiliar with JDT so that could be a false assumption.

**Comment by damieng** [comment]
If  it just requires vmArgs I'll get that into the next release. I already have vmargs working locally - need to PR and merge it :)

**Comment by tylerFowler** [comment]
Awesome! 👍
