### ISSUE TITLE
I just want to know how to compiler and run my code

### ISSUE THREAD

**Issue by lovelyjuice** [atom/ide-java#44]

**Comment by 50Wliu** [comment]
Thanks for reaching out!

For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
