### ISSUE TITLE
Can't resolve packages from Android Studio Project

### ISSUE THREAD

**Issue by justerest** [atom/ide-java#48]
I know it's not a ide-java issue. But I am new in Java and need a little help.
I very like Atom and I want write code of Anroid Studio Project in Atom (I just don't know how write mobile app without Android Studio... Stupid situation).
**Is it possible to configure ide-java for resolving android packages without changing project structure?**
May be VM extra args help me?

**Comment by damieng** [comment]
Unfortunately Android development requires additional capabilities that are beyond those provided in the ide-java package and the underlying language server it uses Eclipse.JDT - specifically in their README

>Limited Gradle support (Android projects are not supported)

https://github.com/eclipse/eclipse.jdt.ls/blob/master/README.md
