### ISSUE TITLE
Add configuration to override default location of `bin` directories

### ISSUE THREAD

**Issue by TimothyMDean** [atom/ide-java#49]
Whenever ide-java is enabled, it appears to create a `bin` folder next to each `src` folder in my project. Inside that folder I see a class directory structure that mirrors my source tree. I presume this is where class files and anything else generated by the java language server get stored.

I'd like the ability to configure ide-java so that it uses a different location for these files. Without that option being available, my Git package sees these files as additions that need to be staged. Of course I could add them to my Git ignore file, but because I already have bin directories elsewhere in my project that I *do* want committed to git, it isn't necessarily trivial to ignore these auto-generated files.

**Comment by damieng** [comment]
Any such creation of folders would be controlled by the underlying language server we use - the Eclipse JDT.  

You can find their repository at https://github.com/eclipse/eclipse.jdt.ls
