### ISSUE TITLE
Add atom-ide-ui as a package dependency

### ISSUE THREAD

**Issue by ghisvail** [atom/ide-java#50]
Since the following is written in the README:

```
This package is currently an early access release. You should also install the atom-ide-ui package to expose the functionality within Atom.
```

It would make sense to add `atom-ide-ui` (and perhaps `language-java` for completeness) to `package-deps`? This way, a user installing `ide-java` would really get the IDE experience without manually installing other packages? This is what is currently done for [atom-ide-rust](https://github.com/mehcode/atom-ide-rust/blob/6e8e248c0218d333c9346673945334e389b8fffc/package.json#L13), or perhaps it is a mistake.

**Comment by damieng** [comment]
It's highly recommended but you can get some functionality with Linter and base Atom (autocomplete). 

More importantly though it also works great with Nuclide which is a superset of atom-ide-ui.
