### ISSUE TITLE
IDE-Java encounted an error using the Java runtime. Exit code 0

### ISSUE THREAD

**Issue by HankelBao** [atom/ide-java#51]
"IDE-Java encounted an error using the Java runtime.
Exit code 0"
I was able to use it yesterday, but today when I opened the same java file, I met this error without further descriptions.
What's wrong with it and how to solve it, please?

I'm using Archlinux and the java runtime package named "jre9-openjdk"

**Comment by franmartosr** [comment]
I experienced the same problem; in my case when I installed the package it didn't do anything (like it wasn't installed) and then when I restarted the editor this error was thrown.

I use Atom 1.23.3 and my Java version is that:
```
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```

**Comment by rsese** [comment]
@HankelBao can you still reproduce now?  If so, what actions lead to the error?  Can you see if there's a more detailed error in devtools console?

http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-for-errors-in-the-developer-tools

@franmartosr what operating system are you running and do you see anything in devtools console?

**Comment by rsese** [comment]
No reply from the OP to our questions in https://github.com/atom/ide-java/issues/51#issuecomment-358459854 and no recent reports so we'll close for now.  Glad things started working for you @franmartosr :+1:

**Comment by ryanyz10** [comment]
I am also getting this error on MacOS 10.13.4, Atom 1.25.1, JDK 10.0.1. When I disable and re-enable *java-ide* in package settings, the language server starts fine.

Looking in the debugger, there are two errors:
`
.atom/packages/ide-java/node_modules/atom-languageclient/build/lib/server-manager.js:5
Uncaught (in promise) undefined
`
