### ISSUE TITLE
JSP capabilities

### ISSUE THREAD

**Issue by danielct1995** [atom/ide-java#52]
Hello everyone, I guess it would be nice to have all java features in .jsp files.
Specifically I am talking about to provide jsp files the same features that are available for java according to the specific syntax of that kind of files. I guess that means to apply JDT server capabilities to code parts that are between <% %> or even <%= %>, at least.

**Comment by damieng** [comment]
The language server protocol and specification doesn't today cope with embedded syntax/grammars.  Unless the language server supports .jsp files directly or the specification changes our hands are tied here.
