### ISSUE TITLE
Atom reports errors for valid imports and variable declarations

### ISSUE THREAD

**Issue by Prrmod** [atom/ide-java#53]
I've set the Java Home directory correctly. For some reasons, ATOM reports "class cannot be resolved to a type" error for the import statements and variables. How to fix this problem?

**Comment by rsese** [comment]
Thanks for the report - do you have a project we can use to reproduce the error?

**Comment by rsese** [comment]
We'll go ahead and close for now since there's no reply to our question in https://github.com/atom/ide-java/issues/53#issuecomment-359079216 but we can re-open if you can help us reproduce.
