### ISSUE TITLE
How to specify custom classpath?

### ISSUE THREAD

**Issue by sriharshachilakapati** [atom/ide-java#61]
One of our apps require some Java scripting, and for the scripts project, we only want to add the selected dependencies. Is it possible to override the classpath? I don't want to be using Gradle or Maven for this, but how does that work?

**Comment by damieng** [comment]
>* What that server can do - syntax compatibility, whether it supports formatting or outlines etc - is outside of our control

You'll need to ask this question upstream to the underling Eclipse JDT that does most of the work https://github.com/eclipse/eclipse.jdt.ls
