### ISSUE TITLE
Class Path is Incomplete.

### ISSUE THREAD

**Issue by ShanuDey** [atom/ide-java#65]
Classpath is incomplete. Only syntax errors will be reported
Eclipse JDT
More Information      Don't Show Again

How can I fix this?

**Comment by damieng** [comment]
Click more information and you will be taken to the wiki page https://github.com/atom/ide-java/wiki/Incomplete-Classpath-Warning

Basically your java project needs a project file that tells it where the classpath is. Either pom.xml or build.gradle file is required. If you already have one of these you should make sure that the folder you open from Atom is the one that contains it at the top level.
