### ISSUE TITLE
Yet another incomplete class path

### ISSUE THREAD

**Issue by AlexGustafsson** [atom/ide-java#94]
Sorry for yet another issue regarding the missing classpath. I've read most of the existing ones but I couldn't proceed with fixing this myself. I read #37 which is a close match, but there it says the issue was fixed in 0.6.6 (I'm on 0.8.3).

![image](https://user-images.githubusercontent.com/14974112/51072358-a5bf6980-165f-11e9-86f9-ed4a66a7af62.png)

As this image shows, no matter what java file I open I get the incomplete classpath error even though I clearly have `build.gradle` in the same project folder. I've used the project opened for a long time and I've seen no misconfiguration regarding Gradle itself.

This is not an Android application, just pure Java which the upstream JDT server seems to support.

**Comment by Bobotic00** [comment]
Just have the same problem what i try is install the older version and it work

**Comment by 50Wliu** [comment]
Tentatively closing as there is a good chance this has been resolved by the upgrade to version 0.39.0 of the language server.
