### ISSUE TITLE
java-ide not compatible with newer atom-versions

### ISSUE THREAD

**Issue by cblusplus** [atom/ide-java#95]
Current versions of Atom.io use a newer node.js version, which is incompatible with the java-ide-plugin. I changed the call of fs.mkdir in the main.js in order to use the plugin with the current atom version.
Replace fs.mkdir(dataDir) on Line 167 with
fs.mkdir(dataDir,{ recursive: true }, (err) => { if (err) throw err; })

**Comment by pfgithub** [comment]
If that fixes it, you should submit a pull request

**Comment by Aerijo** [comment]
@cblusplus Atom does not currently use Electron 3.0 / Node 10+, but I have put in a PR to prevent the issue from occuring.
