### ISSUE TITLE
How can I tell ide-java to ignore specific warnings?

### ISSUE THREAD

**Issue by midnightmilloir** [atom/ide-java#99]
Ide-java is showing a warning on every single one of my HttpServlet classes: `The serializable class <MyClass> does not declare a static final serialVersionUID field of type long`. Is there currently a way to ignore this warning?

**Comment by 50Wliu** [comment]
The Eclipse language server doesn't allow for customization of error reporting. You would probably be best off using the [`@SuppressWarning`](https://docs.oracle.com/javase/8/docs/api/java/lang/SuppressWarnings.html) annotation instead.
